---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbt-grpc
  namespace: csi-cbt
  labels:
    role: grpc
spec:
  selector:
    matchLabels:
      role: grpc
  replicas: 1
  template:
    metadata:
      labels:
        role: grpc
    spec:
      containers:
      - name: grpc
        image: quay.io/isim/cbt-grpc:latest
        command:
        - "./grpc-server"
        ports:
        - name: grpc
          containerPort: 9779
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cbt-grpc
  namespace: csi-cbt
  labels:
    role: grpc
spec:
  ports:
  - name: grpc
    port: 9779
    protocol: TCP
  selector:
    role: grpc
