---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbt-aggapi
  namespace: csi-cbt
  labels:
    api: cbt
    apiserver: "true"
spec:
  selector:
    matchLabels:
      api: cbt
      apiserver: "true"
  replicas: 1
  template:
    metadata:
      labels:
        api: cbt
        apiserver: "true"
    spec:
      containers:
      - name: apiserver
        image: quay.io/isim/cbt-aggapi:latest
        volumeMounts:
        - name: apiserver-certs
          mountPath: /apiserver.local.config/certificates
          readOnly: true
        command:
        - "./apiserver"
        env:
        - name: GRPC_TARGET
          value: cbt-grpc.csi-cbt:9779
        args:
        - "--etcd-servers=http://etcd-svc:2379"
        - "--tls-cert-file=/apiserver.local.config/certificates/tls.crt"
        - "--tls-private-key-file=/apiserver.local.config/certificates/tls.key"
        - "--audit-log-path=-"
        - "--feature-gates=APIPriorityAndFairness=false"
        - "--audit-log-maxage=0"
        - "--audit-log-maxbackup=0"
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
      volumes:
      - name: apiserver-certs
        secret:
          secretName: cbt
---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: cbt
  namespace: csi-cbt
  labels:
    api: cbt
    apiserver: "true"
data:
  tls.crt:
  tls.key:
---
apiVersion: v1
kind: Service
metadata:
  name: cbt
  namespace: csi-cbt
  labels:
    api: cbt
    apiserver: "true"
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
  selector:
    api: cbt
    apiserver: "true"
