apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.cbt.storage.k8s.io
  labels:
    api: cbt
    apiserver: "true"
spec:
  version: v1alpha1
  group: cbt.storage.k8s.io
  groupPriorityMinimum: 2000
  service:
    name: cbt-aggapi
    namespace: csi-cbt
  versionPriority: 10
  caBundle: ""
