---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbt-http
  namespace: csi-cbt
  labels:
    role: http
spec:
  selector:
    matchLabels:
      role: http
  replicas: 1
  template:
    metadata:
      labels:
        role: http
    spec:
      containers:
      - name: http
        image: quay.io/isim/cbt-http:latest
        command:
        - "./http-server"
        args:
        - "--listen-addr=:8080"
        - "--grpc-target=cbt-grpc:9779"
        env:
        - name: CSI_DRIVER_NAME
          value: example.csi.k8s.io
        - name: CSI_CBT_ENDPOINT
          value: http://cbt-http:8080
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
---
apiVersion: v1
kind: Service
metadata:
  name: cbt-http
  namespace: csi-cbt
  labels:
    role: http
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    role: http
