apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-driver
  namespace: csi-cbt
  labels:
    role: csi-driver
spec:
  selector:
    matchLabels:
      role: csi-driver
  replicas: 1
  template:
    metadata:
      labels:
        role: csi-driver
    spec:
      containers:
      - name: grpc
        image: quay.io/isim/cbt-grpc:latest
        command:
        - "./grpc-server"
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
        volumeMounts:
          - name: socket-dir
            mountPath: /run/csi
      - name: http
        image: quay.io/isim/cbt-http:latest
        command:
        - "./http-server"
        args:
        - "--listen-addr=:8080"
        env:
        - name: CSI_DRIVER_NAME
          value: example.csi.k8s.io
        - name: SVC_NAME
          value: cbt-http
        - name: SVC_PORT
          value: "8080"
        - name: SVC_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi
        volumeMounts:
          - name: socket-dir
            mountPath: /run/csi
      volumes:
      - name: socket-dir
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cbt-http
  namespace: csi-cbt
  labels:
    role: csi-driver
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  selector:
    role: csi-driver
